language: node_js
before_script: make
script: make travis
env:
  global:
    - SAUCE_USERNAME=josh-async-form
    - SAUCE_ACCESS_KEY=3930526b-81b3-4d50-9ca9-0fa31edbc1aa
addons:
  sauce_connect: true
